apiVersion: apps/v1
kind: Deployment
metadata:
  name: hero-front
spec:
  selector:
    matchLabels:
      app: hero-front
      tier: frontend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: hero-front
        tier: frontend
        track: stable
    spec:
      containers:
        - name: nginx
          image: "jakejasminjk/hero-frontend:latest"
          lifecycle:
            preStop:
              exec:
                command: ["/usr/sbin/nginx","-s","quit"]